### PR TITLE
Adding projects attributes relating to fixed fee projects

### PR DESCRIPTION
**Pull request by nickfogler**
Hoping this is as simple as adding these in here without any work required in __init__.py

### CODE REVIEW

**Comment by cmerrick** [comment]
Hi @nickfogler, thanks for your contribution!

In order for us to evaluate and accept your PR, we ask that you [sign a contribution license agreement](https://stitch-cla-enforcer.herokuapp.com/). It's all electronic and will take just minutes.

**Comment by cmerrick** [comment]
You did it @nickfogler!

Thank you for signing the Singer Contribution License Agreement.

**Comment by nick-mccoy** [comment]
This change is a subset of the comprehensive updates in [#20].  We will be reviewing that update shortly, so standby!

**Comment by nickfogler** [comment]
Woot!  V2 FTW.  Thanks guys!

**Pull request closed without merging**
